### ISSUE TITLE
Venues and Safety Compliance Overview ticket

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Ops-Programme#156]
**Description:** 
Finalize and confirm venue arrangements for the upcoming ITD course, ensuring all locations meet fire safety and accessibility standards. Share details with volunteers and staff, including entry/exit times, contacts, and contingency plans.
Start Date: 15th of the previous month
Completion Date: 20th of the previous month

**Acceptance Criteria:**

- [x] #205
- [x] #206
- [x] #207
- [x] A contact for the venue in case of problems/emergency (if not somebody from the venue on site)

Regions:
- London
- Sheffield
- North West
- West Midlands
- Scotland

Related documents:
[What we need to cover to hold a class: Ops, Logistics, Risks ](https://docs.google.com/document/d/1nU0dBSXTx0h0sr0SW2YuyX754meMwfhoygD44oyrOiA/edit?usp=sharing)
[Venues Management - Internal (Staff) Use Only
](https://docs.google.com/spreadsheets/d/1KME3B9O4hlvIob9wgZoKGkouiyTu7moqxyIeN_-dwQw/edit?gid=306423760#gid=306423760)
[PM Venue Safety - risks / fire / evacuation plans](https://docs.google.com/spreadsheets/d/1VsJTEqD6ZPyvsyFZqvAbrO3x0L6vp4qn9blIZDFOYg4/edit?gid=472326647#gid=472326647)

[Similar to this ticket Sally made](https://github.com/CodeYourFuture/Ops-Programme/issues/150), which I have closed but keeping here for reference.

**Comment by AmyCYF** [comment]
@cynthimicallef101 how is the list of the contact numbers in case of an emergency for each venue coming?

**Comment by cynthimicallef101** [comment]
@AmyCYF most venues are not giving us an emergency contact number. They say the emergency contact numbers are placed in the buildings. This makes sense, as we might have outdated information in our docs if the numbers change. Also, in case of an emergency, people will not look in a doc, but take action to what is in front of them. All these buildings are managed outside of CYF. Apart from London Brixton where we are tenants, we can only do what they give us and we have to follow their procedures rather than us managing them. 
London Brixton - yes
Sheffield: Emergency contact numbers are placed in view for uses of the building alongside a fire assembly point
Manchester DF Capital: updated
Aston Uni: emergency phone and security staff will help you out of the building.
Strathclyde Uni - same thing, they did not specify an emergency contact number and they said repeatedly emergency information is situated in the building. They are happy to do a one-off in-person session.
